site_name: Login Cidadão
site_description: Torne seu serviços públicos mais eficientes através da adoção de um sistema de autenticação único!
pages:
  - Sobre a plataforma: 'index.md'
  - Deploy:
      - 'Instalação': lc_deploy.md
  - Configurações:
      - 'Configurações': lc_config.md
      - 'Configurando Logout Remote': lc_config_logout_remote.md
      - 'Configurando SSL': lc_config_ssl.md
      - 'Configurando Serviços Terceiros': lc_config_third_part_services.md
  - API:
      - 'Usando a API': lc_api.md
      - 'Enviando notificações': lc_api_sending_notifications.md
  - Desenvolvimento:
      - 'Integração com outras aplicações': lc_develop_integration.md
      - 'Desenvolvimento com aplicações Java': lc_develop_connecting_with_java_aplications.md
      - 'Desenvolvimento com aplicações php 5.2': lc_develop_connecting_with_php5.2_applications.md
      - 'Desenvolvimento com aplicações php 5.3': lc_develop_connecting_with_php5.3_applications.md
      - 'Scopes': lc_develop_scopes.md
markdown_extensions:
  - fenced_code
  - codehilite
copyright: Licenciado através da <a href="https://www.gnu.org/licenses/agpl-3.0.html" target="_blank">AGPL V3</a>.
site_favicon: images/favicon.ico
theme: readthedocs
